---
title: "Appendix"
author: "APB"
date: "7/23/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r load libraries, include = FALSE, warning = FALSE, message = FALSE}
devtools::install_github("zeehio/facetscales")
library(ggplot2)
library(patchwork)
library(tidyverse)
library(cowplot)  
library(here)
library(facetscales)
require(facetscales)
library(lme4)
#library(countreg)
library(MASS)
library(pscl)
library(flextable)
library(betareg)
library(emmeans)
library(survival)
```

# Comparison of spore counts using flow cytometry to traditional counts using a hemocytometer in 'Standard' genotype
```{r spore_check, echo = FALSE}
sporecheck<-read.csv(here("01_Data", "Alaina_counted_Standard_spores.csv"))

sporecheck %>%
  ggplot(mapping=aes(x=sp.ul, y = flow_sp_ul))+
  geom_point()+
  geom_smooth(method= "lm")+
  labs(x = "Spore yield counted by eye (sp/ul)", y = "Spore yield measured using Flow Cytometry (sp/ul)")
```

```{r}
fit<-lm(sp.ul ~ flow_sp_ul - 1, data = sporecheck) 
# R squared
summary(fit)$r.squared
```

## Survival Analyses
```{r survival, echo = FALSE}
inf1<-readRDS('inf1.RDS')
recsurv <- survival::Surv(inf1$meandaydeath, inf1$censored)

# survfit fits survival curves with various methods
# Kaplan-Meier is most common, so use that if in doubt

#fit.KM <- survival::survfit(recsurv ~ 1, type = "kaplan-meier", conf.type = "log-log")
#fit.FM <- survival::survfit(recsurv ~ 1, type = "fleming-harrington", conf.type = "log-log")
#fit.FM2<- survival::survfit(recsurv ~ 1, type = "fh2", conf.type = "log-log")

# print restricted mean
# # of events = the # of animals that died
#print(fit.KM, print.rmean = TRUE)

# plot cummulative harzard, and other mods as
# what's the percentage of animals that die?
#plot(fit.KM, fun = "cumhaz")

# cumulative events (f(y)=1-y)
#plot(fit.KM, fun = "event")

#### Survival Analyses ####

# Now, examine if any of the genotypes differ and by spores
inf1$grouped <- with(inf1, interaction(Spore_level, Infected_Uninfected))

#A45
geno1 <- with(inf1, subset(inf1, Genotype == "A45"))
attach(geno1)

recA45 <- survival::Surv(meandaydeath, censored)
fitA45 <- with(geno1, fit <- survival::survfit(recA45 ~ geno1$grouped, type = "kaplan-meier", conf.type = "log-log"))
plot(fitA45, col = c("darkcyan", "cyan", "darkmagenta", "magenta", "black"), main = "A45", xlab= "Days since exposure", ylab = "Survival", ylim= range(0.5,1))
legend(x = 'bottomleft', c("0", "150 Uninfected", "150 Infected", "300 Uninfected", "300 Infected"),  lty = 1, bty  ='n', col = c("darkcyan", "cyan", "darkmagenta", "magenta", "black"), cex = 0.90)

# Midland 252
geno2 <- with(inf1, subset(inf1, Genotype == "Midland 252"))
attach(geno2)

recM252 <-survival::Surv(meandaydeath, censored)
fit252 <- with(geno2, fit <- survival::survfit(recM252 ~ geno2$grouped, type = "kaplan-meier", conf.type = "log-log"))
plot(fit252,col = c("darkcyan", "cyan", "darkmagenta", "magenta", "black"), main = "M252", xlab= "Days since exposure", ylab = "Survival", ylim= range(0.5,1))
```

## Survival Analyses Continued
```{r continued, echo = FALSE}

#Midland 281
geno3 <- with(inf1, subset(inf1, Genotype == "Midland 281"))
attach(geno3)

recM281 <- survival::Surv(meandaydeath, censored)
fit281 <- with(geno3, fit <- survival::survfit(recM281 ~ geno3$grouped, type = "kaplan-meier", conf.type = "log-log"))
plot(fit281, col = c("darkcyan", "cyan", "darkmagenta", "magenta", "black"), main = "M281", xlab= "Days since exposure", ylab = "Survival", ylim= range(0.5,1))
legend(x = 'bottomleft', c("0", "150 Uninfected", "150 Infected", "300 Uninfected", "300 Infected"),  lty = 1, bty  ='n', col = c("darkcyan", "cyan", "darkmagenta", "magenta", "black"), cex = 0.90)

#Standard
geno4 <- with(inf1, subset(inf1, Genotype == "Standard"))
attach(geno4)

recSTD <- survival::Surv(meandaydeath, censored)
fitSTD <- with(geno4, fit <- survival::survfit(recSTD ~ geno4$grouped, type = "kaplan-meier", conf.type = "log-log"))
plot(fitSTD, col = c("darkcyan", "cyan", "darkmagenta", "magenta", "black"), main = "STD",  xlab= "Days since exposure", ylab = "Survival", ylim= range(0.5,1))
```


## Impacts of Feeding Behavior
```{r plotting feeding rates and host longevity (mean day of death),  echo = FALSE}
inf2<-readRDS('inf2.RDS')

plotlifespan <- inf2 %>% 
  ggplot(aes(y = meandaydeath, 
             x = meanfeedrate, 
             ymin = meandaydeath - sedeathday,
             ymax = meandaydeath + sedeathday, 
             shape = as.factor(Spore_level),
             color = as.factor(Genotype)))+
  #geom_point(position = position_dodge(0.2), size = 2)+
  geom_errorbar(aes(ymin = meandaydeath - sedeathday,
                    ymax = meandaydeath + sedeathday,
                    width = 0)) +
  geom_errorbarh(aes(xmin = meanfeedrate - sefeedrate, 
                     xmax = meanfeedrate + sefeedrate,
                     height = 0)) +
  geom_point(position = position_dodge(0.2), size = 4) +
  ylab("Lifespan (mean day of death)") + 
  labs(x = expression("LN Feeding rate (mL"^-1* ind^-1* hr^-1*")")) +
  theme(panel.spacing = unit(1.05, "lines"),
        panel.border = element_rect(color = "black", 
                                    fill = NA, size = 0.75))+  
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(legend.position = "none")
  #labs(shape = "Pathogen dose", color = "Host genotype") 
plotlifespan

plotdayfirstclutch <- inf2 %>% 
  ggplot(aes(y = meandayfirstclutch, 
             x = meanfeedrate, 
             ymin = meandayfirstclutch - sefirstclutch,
             ymax = meandayfirstclutch + sefirstclutch, 
             shape = as.factor(Spore_level),
             color = as.factor(Genotype)))+
  geom_point(position = position_dodge(0.2), size = 2)+
  geom_errorbar(aes(ymin = meandayfirstclutch - sefirstclutch,
                    ymax = meandayfirstclutch + sefirstclutch,
                    width = 0)) +
  geom_errorbarh(aes(xmin = meanfeedrate - sefeedrate, 
                     xmax = meanfeedrate + sefeedrate,
                     height = 0)) +
  geom_point(position = position_dodge(0.2), size = 4) +
  ylab("Day of first reproduction") + 
  labs(x = expression("LN Feeding rate (mL"^-1* ind^-1* hr^-1*")")) +
  theme(panel.spacing = unit(1.05, "lines"),
        panel.border = element_rect(color = "black", 
                                    fill = NA, size = 0.75))+  
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) 

plotdayfirstclutch
```

\newpage
# Table 2
```{r stats Table 2 feeding rates and infectin stats,  echo = FALSE}
total<-readRDS('total.RDS')
#### Model: Does mean feeding rate differ across spore levels, genotype, and infection status? ####
#### Full model - singular so doesn't converge.
# mod1a <- glm(mean_feeding_rate ~ Genotype*Size_mm2*Infected_Uninfected*Spore_level, 
#              family = gaussian(link = "log"),
#              data = total) 
# 
# summary(mod1a)
# car::Anova(mod1a, type = 'III')

#### Next attempt at full model - interaction terms render the model singular, so do not include
mod1b <- glm(mean_feeding_rate ~ Genotype*Size_mm2 + Infected_Uninfected + Spore_level,
            family = gaussian(link = "log"),
            data = total) 

summary(mod1b)
car::Anova(mod1b, type = 'III')
car::Anova(mod1b, test = "LR")


mod1c <- glm(mean_feeding_rate ~ Genotype + Size_mm2 + Infected_Uninfected + Spore_level,
             family = gaussian(link = "log"),
             data = total) 

bbmle::AICctab(mod1b, mod1c)


#plot(mod1c) 
#### Table 2 ####
summary(mod1c)
stats1 <- car::Anova(mod1c, type = 'III')

Term <- rownames(stats1)
stats1 <- cbind(Term, stats1)
autofit(colformat_num(x = flextable(stats1), j = "Pr(>Chisq)", digits = 4))

#### post hoc analysis ####
marginal = emmeans(mod1c, ~ Infected_Uninfected|Genotype)
pairs(marginal)
```

# with size correction
```{r stats feeding rates and infection frequency, echo = FALSE}
#### Susceptibility and Anorexia/Hyperphagia
modfeedinf <- glm(meanfeedrate ~ probinf*finalsize 
                  + Spore_level
                  + Genotype,
                  family = gaussian(link = "identity"),
                  data = inf1)

car::Anova(modfeedinf, type = 'III')


modfeedinfb <- glm(meanfeedrate ~ probinf*finalsize 
                   + Genotype,
                   family = gaussian(link = "identity"),
                   data = inf1)

car::Anova(modfeedinfb, type = 'III')



modfeedinfc <- glm(meanfeedrate ~ probinf*finalsize 
                   + Spore_level
                   + Genotype,
                   family = gaussian(link = "identity"),
                   data = inf1)

car::Anova(modfeedinfc, type = 'III')


modfeedinfd <- glm(meanfeedrate ~ probinf*finalsize 
                   + Genotype,
                   family = gaussian(link = "log"),
                   data = inf1)

car::Anova(modfeedinfd, type = 'III')



bbmle::AICctab(modfeedinf, modfeedinfb, modfeedinfc, modfeedinfd)


#plot(modfeedinfb)
summary(modfeedinfb)
stats1 <- car::Anova(modfeedinfb, type = 'III')
stats1
Term <- rownames(stats1)
stats1 <- cbind(Term, stats1)
autofit(colformat_num(x = flextable(stats1), j = "Pr(>Chisq)", digits = 4))
```

## Impacts of Infection
```{r plotting spore yield (within-host pathogen density) and host growth,  echo = FALSE}
plotgrowthyield <- inf2 %>% 
  ggplot(aes(y = meanspores, 
             x = meangrowth, 
             ymin = meanspores - sespores,
             ymax = meanspores + sespores, 
             shape = as.factor(Spore_level),
             color = as.factor(Genotype)))+
  geom_point(position = position_dodge(0.2), size = 5)+
  geom_errorbar(aes(ymin = meanspores - sespores,
                    ymax = meanspores + sespores,
                    width = 0)) +
  geom_errorbarh(aes(xmin = meangrowth - segrowth, 
                     xmax = meangrowth + segrowth,
                     height = 0)) +
  geom_point(position = position_dodge(0.2), size = 5) +
  labs(y = expression("Spore yield (spores host"^-1* "x 10"^3* ")"))+ 
  labs(x = expression("Total growth (final - initial size, mm"^2*")")) +
  theme(panel.spacing = unit(1.05, "lines"),
        panel.border = element_rect(color = "black", 
                                    fill = NA, size = 0.75))+  
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) +
  theme(legend.position = "none")
plotgrowthyield 

plotfityield <- inf2 %>% 
  ggplot(aes(x = meanspores, 
             y = meanfitnes, 
             xmin = meanspores - sespores,
             xmax = meanspores + sespores, 
             shape = as.factor(Spore_level),
             color = as.factor(Genotype)))+
  geom_point(position = position_dodge(0.2), size = 5)+
  geom_errorbarh(aes(xmin = meanspores - sespores,
                     xmax = meanspores + sespores,
                     height = 0)) +
  geom_errorbar(aes(ymin = meanfitnes - sefitness, 
                    ymax = meanfitnes + sefitness,
                    width = 0)) +
  geom_point(position = position_dodge(0.2), size = 5) +
  labs(x = expression("Spore yield (spores host"^-1* " 10"^3* ")"))+ 
  labs(y = expression("Total reproduction (host" ^-1*")")) +
  theme(panel.border = element_rect(color = "black", 
                                    fill = NA, size = 0.75))+  
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) 
plotfityield
```

\newpage
# Table 5a
```{r stats patterns across all genotypes,  echo = FALSE}
#### Model: Across all genotypes does the probability of infection differ across feeding rates, final body size (surface area), spore levels  ? ####
infected <- total %>% 
  filter(Spore_level > 0, na.rm = TRUE)
#filter(Genotype != "Midland 281")

y <- with(infected, cbind(Infected, (Susceptible + Infected + Exposed)))


#### Across all genotypes ####
mod2m <- glm(y ~ mean_feeding_rate*Size_mm2
             + as.factor(Spore_level),
             family = binomial,
             data = infected) 

mod3m <- glm(y ~ mean_feeding_rate + Size_mm2,
             family = binomial,
             data = infected) 



bbmle::AICctab(mod3m, mod2m)

#### Table 5a ## ####
#plot(mod3m)

summary(mod3m)
stats1 <- car::Anova(mod3m, type = 'III')
stats1
Term <- rownames(stats1)
stats1 <- cbind(Term, stats1)
autofit(colformat_num(x = flextable(stats1), j = "Pr(>Chisq)", digits = 4))
```

# Table 5b (accounting for genetic variation)
```{r stats, feeding rates and infection frequency - when accounting for genotypic differences,  echo = FALSE}

mod2h <- glm(y ~ mean_feeding_rate*Size_mm2
             + as.factor(Genotype)
             + as.factor(Spore_level), 
             family = binomial,
             data = infected) 


car::Anova(mod2h, test = "Wald")


mod2i <- glm(y ~ mean_feeding_rate + Size_mm2
             + as.factor(Genotype)
             + as.factor(Spore_level), 
             family = binomial,
             data = infected) 

car::Anova(mod2i, test = "Wald")



bbmle::AICctab(mod2h, mod2i)

car::Anova(mod2h, type = 'III')

#Table 5b
#plot(mod2j)
stats1 <- car::Anova(mod2h, type = 'III')
stats1
Term <- rownames(stats1)
stats1 <- cbind(Term, stats1)
autofit(colformat_num(x = flextable(stats1), j = "Pr(>Chisq)", digits = 4))
```

# Table 5a Spore yield

```{r stats Table 5a spore yield,  echo = FALSE}
total <- total %>%
  mutate(Spore_level_fct = factor(Spore_level))

# Examine spore yield in animals that were actually infected

totalpos <- total %>% 
  filter(Spores_ul>0)

#### Spore yield and Anorexia
#### Patterns across all genotypes ####

mod2k <- glm(Spores_ul ~ mean_feeding_rate 
             + as.factor(Spore_level), 
             data = total) 

summary(mod2k)
car::Anova(mod2k, type = 'III')
aov(mod2k)

modfeedspores1 <- glm(Spores_ul ~ mean_feeding_rate*Size_mm2 
                     + Spore_level_fct,
                     family = gaussian(link = "identity"),
                     data = totalpos)

car::Anova(modfeedspores1, type = 'III')


modfeedspores2 <- glm(Spores_ul ~ mean_feeding_rate+Size_mm2 
                     + Spore_level_fct*Final_Size_mm2,
                     family = gaussian(link = "identity"),
                     data = totalpos)

car::Anova(modfeedspores2, type = 'III')

modfeedspores3 <- glm(Spores_ul ~ mean_feeding_rate+Size_mm2 
                      + Spore_level_fct+Final_Size_mm2,
                      family = gaussian(link = "identity"),
                      data = totalpos)


modfeedspores4 <- glm(Spores_ul ~ Spore_level_fct+Final_Size_mm2,
                      family = gaussian(link = "identity"),
                      data = totalpos)


car::Anova(modfeedspores4, type = 'III')


AIC(modfeedspores1, modfeedspores2, modfeedspores3, modfeedspores4)



#### Table ####
#plot(modfeedsporesb)
# summary(modfeedsporesb)
# stats1 <- car::Anova(modfeedsporesb, type = 'III')
# stats1
# Term <- rownames(stats1)
# stats1 <- cbind(Term, stats1)
# autofit(colformat_num(x = flextable(stats1), j = "Pr(>Chisq)", digits = 4))
```

# Table 5b Spore yield 
```{r stats Table 5b spore yield,  echo = FALSE, warning = FALSE}

# Examine spore yield in animals that were actually infected

total <- total %>%
  mutate(Spore_level_fct = factor(Spore_level))


totalpos <- total %>% 
  filter(Spores_ul>0)

modfeedspores <- glm(Spores_ul ~ mean_feeding_rate*Size_mm2
                  + Spore_level_fct
                  + Final_Size_mm2
                  + Genotype,
                  family = gaussian(link = "identity"),
                  data = totalpos)

car::Anova(modfeedspores, type = 'III')



modfeedsporesb <- glm(Spores_ul ~ mean_feeding_rate + Size_mm2 
                     + Spore_level_fct
                     + Final_Size_mm2
                     + Genotype,
                     family = gaussian(link = "identity"),
                     data = totalpos)

car::Anova(modfeedsporesb, type = 'III')



modfeedsporesc <- glm(Spores_ul ~ mean_feeding_rate + Size_mm2 
                      + Spore_level_fct
                      + Genotype,
                      family = gaussian(link = "identity"),
                      data = totalpos)

car::Anova(modfeedsporesc, type = 'III')




modfeedsporese <- glm(Spores_ul ~ mean_feeding_rate
                      + Spore_level_fct
                      + Genotype,
                      family = gaussian(link = "identity"),
                      data = total)

car::Anova(modfeedsporese, type = 'III')

modfeedsporesf <- glm(Spores_ul ~ Spore_level_fct
                      + Genotype,
                      family = gaussian(link = "identity"),
                      data = total)

car::Anova(modfeedsporesf, type = 'III')


# 
# bbmle::AICctab(modfeedspores, modfeedsporesb, modfeedsporesc, 
#                modfeedsporese,  modfeedsporesf)




#### Table 5b ####
#plot(modfeedsporesb)
summary(modfeedsporesb)
stats1 <- car::Anova(modfeedsporesb, type = 'III')
stats1
Term <- rownames(stats1)
stats1 <- cbind(Term, stats1)
autofit(colformat_num(x = flextable(stats1), j = "Pr(>Chisq)", digits = 4))


#### post hoc analysis ####
library(emmeans)
marginal = emmeans(modfeedsporesb, ~ Genotype|Spore_level_fct)
pairs(marginal)
```


